import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";

import Footer from "@/components/footer/Footer";
import Search from "@/components/Search/Search";
import NoShow from "@/components/noShow/NoShow";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BuyTech",
  description: "Generated by BuyTech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NoShow>
          <NavBar />
          <Search />
        </NoShow>
        {children}
        <NoShow>
          <Footer />
        </NoShow>
      </body>
    </html>
  );
}
